'use client';

import { Amplify } from 'aws-amplify';
import {
  signIn,
  signOut,
  getCurrentUser,
  fetchAuthSession,
  type SignInInput,
} from 'aws-amplify/auth';

// Configure Amplify Auth with Cognito User Pool
// In production, these values come from amplify_outputs.json generated by Amplify Gen 2
const amplifyConfig = {
  Auth: {
    Cognito: {
      userPoolId: process.env.NEXT_PUBLIC_USER_POOL_ID || '',
      userPoolClientId: process.env.NEXT_PUBLIC_USER_POOL_CLIENT_ID || '',
      identityPoolId: process.env.NEXT_PUBLIC_IDENTITY_POOL_ID || '',
    },
  },
};

let isConfigured = false;

export function configureAmplify() {
  if (!isConfigured) {
    Amplify.configure(amplifyConfig, { ssr: true });
    isConfigured = true;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Auth Operations
// ─────────────────────────────────────────────────────────────────────────────

export interface AuthUser {
  userId: string;
  email: string;
  orgId: string;
  role: 'Admin' | 'Manager' | 'Employee';
  name?: string;
}

export async function login(email: string, password: string): Promise<AuthUser> {
  const input: SignInInput = {
    username: email,
    password,
  };

  const result = await signIn(input);

  if (result.isSignedIn) {
    return getAuthUser();
  }

  throw new Error('Sign in was not completed. Please check your credentials.');
}

export async function logout(): Promise<void> {
  await signOut();
}

export async function getAuthUser(): Promise<AuthUser> {
  const session = await fetchAuthSession();
  const idToken = session.tokens?.idToken;

  if (!idToken) {
    throw new Error('No valid session found');
  }

  const claims = idToken.payload;

  return {
    userId: (claims['sub'] as string) || '',
    email: (claims['email'] as string) || '',
    orgId: (claims['custom:orgId'] as string) || '',
    role: (claims['custom:role'] as 'Admin' | 'Manager' | 'Employee') || 'Employee',
    name: (claims['name'] as string) || undefined,
  };
}

export async function getAccessToken(): Promise<string> {
  const session = await fetchAuthSession();
  const accessToken = session.tokens?.accessToken?.toString();

  if (!accessToken) {
    throw new Error('No valid access token');
  }

  return accessToken;
}

export async function getIdToken(): Promise<string> {
  const session = await fetchAuthSession();
  const idToken = session.tokens?.idToken?.toString();

  if (!idToken) {
    throw new Error('No valid ID token');
  }

  return idToken;
}

export async function isAuthenticated(): Promise<boolean> {
  try {
    await getCurrentUser();
    return true;
  } catch {
    return false;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Inactivity Timeout (30 minutes)
// ─────────────────────────────────────────────────────────────────────────────

const INACTIVITY_TIMEOUT_MS = 30 * 60 * 1000; // 30 minutes

let inactivityTimer: ReturnType<typeof setTimeout> | null = null;
let onTimeoutCallback: (() => void) | null = null;

function resetInactivityTimer() {
  if (inactivityTimer) {
    clearTimeout(inactivityTimer);
  }

  inactivityTimer = setTimeout(() => {
    if (onTimeoutCallback) {
      onTimeoutCallback();
    }
  }, INACTIVITY_TIMEOUT_MS);
}

const activityEvents = ['mousedown', 'mousemove', 'keydown', 'scroll', 'touchstart', 'click'];

export function startInactivityMonitor(onTimeout: () => void): () => void {
  onTimeoutCallback = onTimeout;
  resetInactivityTimer();

  const handleActivity = () => {
    resetInactivityTimer();
  };

  activityEvents.forEach((event) => {
    document.addEventListener(event, handleActivity, { passive: true });
  });

  // Return cleanup function
  return () => {
    if (inactivityTimer) {
      clearTimeout(inactivityTimer);
      inactivityTimer = null;
    }
    onTimeoutCallback = null;
    activityEvents.forEach((event) => {
      document.removeEventListener(event, handleActivity);
    });
  };
}
